# Generated by Django 4.2.7 on 2025-08-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('admin', 'Hospital Staff'), ('superuser', 'Hospital IT')], default='patient', max_length=10),
        ),
    ]
