# Generated by Django 4.2.7 on 2025-08-03 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('treatment_complete', 'Treatment Complete'), ('weekly_summary', 'Weekly Summary'), ('monthly_summary', 'Monthly Summary'), ('discharge_summary', 'Discharge Summary')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('compliance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_medications', models.IntegerField(default=0)),
                ('taken_medications', models.IntegerField(default=0)),
                ('missed_medications', models.IntegerField(default=0)),
                ('report_period_start', models.DateField()),
                ('report_period_end', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
